### ISSUE TITLE
对抗损失

### ISSUE THREAD

**Issue by xxxnb** [LZ-CH/Exposure_Correction-pytorch#1]
你好，请问你测试了使用对抗损失后的结果吗，我使用之后会出现图像全黑的问题。

**Comment by LZ-CH** [comment]
你好，那个对抗损失之前是有测试过的，你看看前面阶段(前几阶段是未使用对抗损失的)里在run-out里的过程图像能正常不?

**Comment by LZ-CH** [comment]
如果前面阶段也都是全黑的话，你可以先检验一下你那处理后的pach文件夹里的图像是否能够一一对应了(我在早期复现阶段时也是遇到过不匹配的问题，导致训练出的图像为全黑的)

**Comment by xxxnb** [comment]
感谢大佬指导，问题已解决。
