### ISSUE TITLE
[Feature Requested] Running Time

### ISSUE THREAD

**Issue by orzanai** [LZ-CH/Exposure_Correction-pytorch#11]
Hello, thank you for your contributions in this field, it is really nice to have Python implementation of this model. Much appreciated.

I want to ask you about the running time of the model in the testing phase. Could you add this information by any chance? 

Thanks in advance!

**Comment by LZ-CH** [comment]
I process pictures one by one. The whole test process takes about 1 hour, while using bgu for subsequent processing takes about 10 hours.
