### ISSUE TITLE
Training input

### ISSUE THREAD

**Issue by caaxgave** [LZ-CH/Exposure_Correction-pytorch#12]
Hello, thanks in advance for your contribution. I have a question regarding the training phase. It is known that this architecture enhance both over and underexposed errors, however, I don´t understand exactly how it should be trained, in a separate way first with overexposed dataset and their ground truth, then with underexposed dataset and their graundtruth in such a way we end up with two different weights, or should I convine both datasets with their ground truth in such a way to have only one model (weights) which can be used to test any image with any exposure errors?

thank you!

**Comment by LZ-CH** [comment]
The training dataset contains images of 5 different levels of exposure conditions, and then train only one model that can handle both underexposed and overexposed images.
