### ISSUE TITLE
关于训练过程生成异常

### ISSUE THREAD

**Issue by raoning-5** [LZ-CH/Exposure_Correction-pytorch#13]
你好，感谢开源。
我把高曝光的图片从数据集中筛选了出来，除了路径和数据集没有改过其他代码了。
可以正常训练，但是在run-out中得到的train-output图片显示异常，不知道是什么原因，您可以看看不，感谢。
贴图为train-output1和train-output4
<img width="1090" alt="train-output1" src="https://user-images.githubusercontent.com/73412803/222033161-3efc5aaf-bc57-40c3-b3d6-c967f4e83c1b.png">

<img width="1093" alt="train-output4" src="https://user-images.githubusercontent.com/73412803/222033206-9fd21589-a391-4620-b312-c000f622a300.png">

**Comment by LZ-CH** [comment]
如果是在训练过程中如此，那是正常现象(此时模型还没有收敛)；如果在训练最终时还是如此，那你可以通过先运行多亮度的图，看看你的环境配置有无问题，以及检查数据匹配情况，也不排除本身该作者的模型不太适合只有过曝光的图像调整任务。

**Comment by raoning-5** [comment]
感谢您的回复。
图片是是训练最终时得到的结果，那我来试试多亮度的图，而且只用过曝光的图像训练过程损失也非常非常高，好奇怪
<img width="718" alt="截屏2023-03-01 11 13 23" src="https://user-images.githubusercontent.com/73412803/222035722-81dc55bf-f417-406d-89bc-1ad8968ff355.png">
