### ISSUE TITLE
数据集下载不下来

### ISSUE THREAD

**Issue by ChengYingo** [LZ-CH/Exposure_Correction-pytorch#3]
您好，数据集从官方链接下载不下来，可以麻烦传到网盘一份吗？谷歌、百度都可以。好人一生平安！

**Comment by LZ-CH** [comment]
你好，我刚尝试了官方链接，依旧还能进行下载诶，你可能需要多尝试一下?或者可以使用相关上网工具来加快你的下载速度；由于该数据集并不是我提出的，所以我这边可能不太方便将其放置在个人网盘公开出来(因为不能确保后续官方依旧将该数据集进行开源)，对此表示十分抱歉。
