### ISSUE TITLE
Checkpoint 

### ISSUE THREAD

**Issue by MorganPhobo5** [LZ-CH/Exposure_Correction-pytorch#5]
Hello. Thank you for your work. 
Could you upload checkpoint of model to GoogleDrive, for example? It's very difficult to use Baidu outside of China.

**Comment by LZ-CH** [comment]
I am very sorry that I only saw the issue now, because it is difficult for me to transfer the file to the GoogleDrive. You can contact me by email, and I will send you the weight file by email.
