### ISSUE TITLE
测试效果

### ISSUE THREAD

**Issue by tkone2018** [LZ-CH/Exposure_Correction-pytorch#8]
感谢您的开源哈，我测试你给的模型效果感觉不是很好，我是需要做什么调整吗

**Comment by tkone2018** [comment]
![over_test](https://user-images.githubusercontent.com/41476675/185588000-2c64d324-e09d-4fa5-ab24-826e90beb0a1.jpg)

**Comment by tkone2018** [comment]
模糊有点严重感觉

**Comment by LZ-CH** [comment]
这是因为原本的代码测试时，是采用的先将原图缩小到512*512的大小(原论文的做法也是如此，如若不这么做，效果会很差)，然后处理后才缩放到正常大小(直接上采样，会损失一点细节，当然你也可以使用bgu上采样的方式，那样会减少一些细节损失，不过bgu上采样我尝试过，需要比较长的运行时间)。

**Comment by tkone2018** [comment]
@LZ-CH 哦哦，这样啊，好的，我试试
