### ISSUE TITLE
关于拉普拉斯金字塔实现方式对网络的影响

### ISSUE THREAD

**Issue by Musclemanisme** [LZ-CH/Exposure_Correction-pytorch#9]
你好，感谢开源。
我是对这篇文章的彩图拉普帕斯金字塔实现方式感兴趣才找到这个repo的，自己也试了OpenCV-Python的接口，对于图片相减，OpenCV有两种实现方式：
1.直接相减。这样的话相减的像素值val = img1 - img2，但是如果这个val是负值的话，会被处理成（val + 255） % 255的，比如val = -20，变成235，这样拉普拉斯金字塔的残差图像会是这样一种风格。
![minus](https://user-images.githubusercontent.com/38111433/188399721-b53a0a56-3622-46bc-97a8-65bd3add3727.png)
2.cv2.subtract(img1,img2)，在这个实现方式中，像素不会超过255，所以只考虑负的像素值，负值会被截断成0，整体的残差图像是黑色背景加上图像的细节部分，长这个样子。
![subtract](https://user-images.githubusercontent.com/38111433/188400139-0212032e-7d66-4862-ade5-bac9f0da1f9b.png)
不知道这两种处理方式预处理后的结果对于网络的输出有什么影响，如果模型数据还有计算资源方便的话，可以跑一下对比效果么？
原图
![28](https://user-images.githubusercontent.com/38111433/188400334-216f2356-b8c9-49e2-92d8-ffc502679e0e.png)

**Comment by Musclemanisme** [comment]
后来我又在一个称自己是OpenCV-Python官方中文文档里面，看到了有关图像金字塔的描述，作者使用的也是cv2.subtract()来求拉普拉斯金字塔的残差图像。

**Comment by LZ-CH** [comment]
如果是需要将残差图像保存或者可视化出来的话，是需要去除负值才能正常显示的，但是如果只是作为生成最终图像的中间数据，那么我认为保留全部数据(包括负值)更为恰当。我个人认为cv2.subtract()目的于生成一个图像，因此对负值进行了截断，而在此论文的模型中，应当将残差当成合成最终图像的一个"中间数据"，即使论文有将残差数据通过图可视化了出来。

**Comment by Musclemanisme** [comment]
确实，不是截断的话，残差图像作为中间特征能够包含更多的图像信息。

**Comment by LZ-CH** [comment]
你好，理论上来说，不去除负值的方法更加合理（因为细节损失更少，保留更多的原始信息，我记得原论文也是直接相减的）。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月5日(周一) 下午4:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [LZ-CH/Exposure_Correction-pytorch] 关于拉普拉斯金字塔实现方式对网络的影响 (Issue #9)




 
你好，感谢开源。
 我是对这篇文章的彩图拉普帕斯金字塔实现方式感兴趣才找到这个repo的，自己也试了OpenCV-Python的接口，对于图片相减，OpenCV有两种实现方式：
 1.直接相减。这样的话相减的像素值val = img1 - img2，但是如果这个val是负值的话，会被处理成（val + 255） % 255的，比如val = -20，变成235，这样拉普拉斯金字塔的残差图像会是这样一种风格。
 
 2.cv2.subtract(img1,img2)，在这个实现方式中，像素不会超过255，所以只考虑负的像素值，负值会被截断成0，整体的残差图像是黑色背景加上图像的细节部分，长这个样子。
 
 不知道这两种处理方式预处理后的结果对于网络的输出有什么影响，如果模型数据还有计算资源方便的话，可以跑一下对比效果么？
 原图
